baseURL: "https://tesaunders.github.io/"
languageCode: en-us
theme: PaperMod
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    profileMode:
        enabled: true
        title: "Tom Saunders"
        subtitle: "Digital Skills • Data Management • Open Research"
        imageUrl: "images/profile-pic.jpg"
        imageWidth: 250
        imageHeight: 250
    
    socialIcons:
        - name: "email"
          url: "<link>"
        - name: "github"
          url: "https://github.com/tesaunders"
        - name: "twitter"
          url: "https://twitter.com/TomSaundersNZ"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/tomsaundersnz/"

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: publications
          name: Publications
          url: /publications/
          weight: 20
        - identifier: awards
          name: Awards
          url: /awards/
          weight: 30
        - identifier: media
          name: Media
          url: /media/
          weight: 40
        - identifier: outreach
          name: Outreach
          url: /outreach/
          weight: 50
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 60