baseURL: "https://tesaunders.github.io/"
languageCode: en-us
theme: PaperMod
enableEmoji: true

params:
    profileMode:
        enabled: true
        title: "Tom Saunders"
        subtitle: "Digital Skills • Data Management • Open Research"
        imageUrl: "images/profile-pic.jpg"
        imageWidth: 250
        imageHeight: 250
    
    socialIcons:
        - name: "email"
          url: "<link>"
        - name: "github"
          url: "https://github.com/tesaunders"
        - name: "twitter"
          url: "https://twitter.com/TomSaundersNZ"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/tomsaundersnz/"