baseURL: "https://tomsaunders.me/"
languageCode: en-us
theme: PaperMod
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    profileMode:
        enabled: true
        title: "Tom Saunders"
        subtitle: "Open Research • Digital Skills • Data Management"
        imageUrl: "images/profile-pic.jpg"
        imageWidth: 250
        imageHeight: 250 
    socialIcons:
        - name: "email"
          url: "https://tesaunders.github.io/contact/"
        - name: "github"
          url: "https://github.com/tesaunders"
        - name: "twitter"
          url: "https://twitter.com/TomSaundersNZ"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/tomsaundersnz/"
DateFormat: "02 January 2006"
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: publications
          name: Publications
          url: /publications/
          weight: 20
        - identifier: awards
          name: Awards
          url: /awards/
          weight: 30
        - identifier: outreach
          name: Outreach
          url: /outreach/
          weight: 50
        - identifier: notes
          name: Resources
          url: /resources/
          weight: 60
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 65
        - identifier: contact
          name: Contact
          url: /contact/
          weight: 70